Fix for mixed precision run and their input parameters
ROCm/onnxruntime pull request #39
Opened 2024-06-08 17:08 UTC by TedThemistokleous

Fixes GPU faults Seen when running Mixed Precision inferences workloads with Bert v1.1  (fp16 + int8 Quant of Conv + MatMul)

Was hitting an edge case with mixed precision where the input parameters were not being populated and using uninitizlied values for the parameters which would "work" silently as no issue in inference arise. For bert though, segment_ids is pushed through a gather onnx operator which uses these as an index.

Using uninitialized memory made this error  such that it was non obvious why we were getting failures between our runs and we saw the issue intermittently between machines/cards/etc.

Fixes here are as follows to the MIGraphX Execution Provider

-Fp16 quantization after int8
-Additional debug logging for workflow of loading/quantization
- Set input/output parameters as seperate run prior to int8 calibration
- Set all dynamic data as input parameters for int8 static calibration to be performed with MIGraphX

Without these changes models will fail to copy input parameters on mixed precision runs when we decided to quantize as MIGraphX assumes all inputs will be used for calibration not just the input data read in from a calibration table.

### Description

### Motivation and Context

2024-06-10 21:28 UTC, groenenboomj requested changes
It'll get bounced until it's de-linted but it looks reasonable.  Are there other inputs to check and/or are dot and convolution all that needs quantized?

2024-06-10 21:43 UTC, groenenboomj requested changes

2024-06-10 21:43 UTC, groenenboomj commented on onnxruntime/core/providers/migraphx/migraphx_execution_provider.cc
> +    no_input_shape = no_input_shape or get_input_output_names(graph_body_viewer, input_names, output_names);
Use '||' not 'or' (or make a macro to confuse everyone).

2024-06-10 21:43 UTC, groenenboomj commented on onnxruntime/core/providers/migraphx/migraphx_execution_provider.cc
> +        LOGS_DEFAULT(INFO) << "Quantizing input program to int8" << std::endl;
I'd put this under VERBOSE for logs (same for other logs).

2024-06-11 14:32 UTC, TedThemistokleous commented
> It'll get bounced until it's de-linted but it looks reasonable. Are there other inputs to check and/or are dot and convolution all that needs quantized?

No right now we just quantize MatMul and Conv which resolve to dot, and convolution in MIGraphX. Likely we'll add to this list at a later date

2024-06-11 15:25 UTC, groenenboomj approved these changes

2024-06-11 21:15 UTC, merged